# Generated by Django 3.2.6 on 2021-09-20 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paster', '0002_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=150, verbose_name='Ссылка на пасту')),
                ('count', models.IntegerField(default=0, verbose_name='Количество оценок')),
                ('avg', models.IntegerField(default=0, verbose_name='Средняя оценка')),
            ],
            options={
                'verbose_name': 'Паста',
                'verbose_name_plural': 'Пасты',
            },
        ),
    ]
