# Generated by Django 3.2.6 on 2021-09-20 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paster', '0003_paste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paste',
            name='avg',
        ),
        migrations.RemoveField(
            model_name='paste',
            name='count',
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(default=5, verbose_name='Оценка')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paster.member')),
                ('paste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paster.paste')),
            ],
            options={
                'verbose_name': 'Оценка пасты',
                'verbose_name_plural': 'Оценки паст',
            },
        ),
    ]
