# Generated by Django 3.2.6 on 2021-09-21 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paster', '0004_auto_20210921_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='paste',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст пасты'),
        ),
        migrations.AlterField(
            model_name='paste',
            name='link',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ссылка на пасту'),
        ),
    ]
