# Generated by Django 3.2.6 on 2021-09-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paster', '0005_auto_20210921_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='name',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='Имя'),
        ),
    ]
