# Generated by Django 3.2.6 on 2021-09-23 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paster', '0006_member_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paster.member'),
        ),
    ]
