# Generated by Django 3.2.6 on 2021-09-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paster', '0008_mark_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='paste',
            name='last_relate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
