# Generated by Django 3.2.6 on 2021-09-30 13:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('paster', '0009_paste_last_relate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='paste',
            name='last_relate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
