# Generated by Django 3.2.6 on 2021-11-17 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paster', '0010_auto_20210930_1620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mark',
            options={'ordering': ('-created_at',), 'verbose_name': 'Оценка пасты', 'verbose_name_plural': 'Оценки паст'},
        ),
        migrations.AddField(
            model_name='paste',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paster.member', verbose_name='Отправитель'),
        ),
    ]
