# Generated by Django 3.2.6 on 2022-01-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paster', '0011_auto_20211117_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='paste',
            name='last_publicate',
            field=models.DateField(null=True, verbose_name='Дата последней публикации'),
        ),
    ]
