# Generated by Django 3.2.6 on 2022-01-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paster', '0012_paste_last_publicate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='last_publicate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата последней публикации'),
        ),
    ]
