# Generated by Django 3.2.6 on 2022-01-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paster', '0013_alter_paste_last_publicate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasteTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тег пасты',
                'verbose_name_plural': 'Теги паст',
            },
        ),
        migrations.AddField(
            model_name='paste',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='paster.PasteTag', verbose_name='Теги'),
        ),
    ]
