# Generated by Django 3.2.6 on 2022-01-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paster', '0014_auto_20220121_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_moder',
            field=models.BooleanField(default=False, verbose_name='Модератор?'),
        ),
        migrations.AlterField(
            model_name='paste',
            name='tags',
            field=models.ManyToManyField(blank=True, to='paster.PasteTag', verbose_name='Теги'),
        ),
    ]
