# Generated by Django 3.2.6 on 2022-01-26 19:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('paster', '0016_paste_link_self'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paster.member')),
            ],
            options={
                'verbose_name': 'Действие модера',
                'verbose_name_plural': 'Действия модеров',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ModerTag',
            fields=[
                ('moderaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='paster.moderaction')),
                ('paste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paster.paste', verbose_name='Паста')),
                ('tags', models.ManyToManyField(blank=True, to='paster.PasteTag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Тег модера',
                'verbose_name_plural': 'Теги модеров',
                'ordering': ('-created_at',),
            },
            bases=('paster.moderaction',),
        ),
    ]
