# Generated by Django 3.2.6 on 2022-01-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paster', '0017_moderaction_modertag'),
    ]

    operations = [
        migrations.AddField(
            model_name='paste',
            name='pic_link_self',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка на картинку'),
        ),
        migrations.AddField(
            model_name='paste',
            name='pic_self',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Картинка'),
        ),
    ]
