# Generated by Django 3.2.6 on 2022-01-26 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paster', '0018_auto_20220126_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='pic_link_self',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Ссылка на картинку'),
        ),
    ]
