# Generated by Django 3.2.6 on 2022-11-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paster', '0020_auto_20220730_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField(unique=True, verbose_name='Id паблика')),
                ('name', models.CharField(max_length=100, verbose_name='Имя паблика')),
            ],
            options={
                'verbose_name': 'Источник',
                'verbose_name_plural': 'Источники',
            },
        ),
    ]
