# Generated by Django 3.2.6 on 2024-03-31 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paster', '0021_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasteSuggest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст пасты')),
                ('sender', models.IntegerField(verbose_name='Отправитель')),
                ('sender_nickname', models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя отправителя')),
            ],
            options={
                'verbose_name': 'Паста в предложке',
                'verbose_name_plural': 'Пасты в предложке',
            },
        ),
    ]
